### ISSUE TITLE
ViZDoom & SafetyGym Performance

### ISSUE THREAD

**Issue by MiaAltieri** [scottemmons/sgm#5]
Not really an issue with anything in the code, but I was curious if you plan to upload your code for the ViZDoom and SafetyGym tests that you did in the paper with SPTM and ConSPTM. I'd love to take a look at these! 

Awesome work by the way

**Comment by scottemmons** [comment]
Glad you enjoyed the work! At the moment, we don't have plans to officially support the ViZDoom and SafetyGym environments.
